#define NK_INCLUDE_FIXED_TYPES
#define NK_INCLUDE_STANDARD_IO
#define NK_INCLUDE_STANDARD_VARARGS
#define NK_INCLUDE_DEFAULT_ALLOCATOR

#define NK_IMPLEMENTATION
#include "nuklear.h"

//#define NK_GDI_IMPLEMENTATION
//#include "nuklear_gdi.h"
